// swift-tools-version: 5.9
//
// GurbaniCaptioning — on-device live Gurbani kirtan captioning.
//
// Architecture mirrors src/engine.py + src/streaming_engine.py (Python). The
// CaptionEngine class wraps WhisperKit (ANE-accelerated Core ML inference)
// and routes its transcript output through FuzzyMatcher + ShabadStateMachine
// to produce canonical SGGS line predictions.
//
// Open this Package.swift in Xcode — it generates the project tree directly,
// no .xcodeproj hand-authoring needed.

import PackageDescription

let package = Package(
    name: "GurbaniCaptioning",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "GurbaniCaptioning",
            targets: ["GurbaniCaptioning"]
        ),
        .executable(
            name: "GurbaniCaptioningApp",
            targets: ["GurbaniCaptioningApp"]
        ),
    ],
    dependencies: [
        // On-device Whisper inference on Apple Silicon. Argmax's package
        // handles audio capture, Core ML model loading, ANE optimization,
        // word-level timestamps via DTW on cross-attention.
        .package(url: "https://github.com/argmaxinc/WhisperKit", from: "0.9.0"),
    ],
    targets: [
        .target(
            name: "GurbaniCaptioning",
            dependencies: [
                .product(name: "WhisperKit", package: "WhisperKit"),
            ],
            path: "Sources/GurbaniCaptioning",
            resources: [
                // Corpus JSON is generated by scripts/build_ios_corpus.py and
                // dropped into Sources/GurbaniCaptioning/Resources/. The
                // bundle ships it to the device.
                .process("Resources"),
            ]
        ),
        .executableTarget(
            name: "GurbaniCaptioningApp",
            dependencies: ["GurbaniCaptioning"],
            path: "Sources/GurbaniCaptioningApp"
        ),
        .testTarget(
            name: "GurbaniCaptioningTests",
            dependencies: ["GurbaniCaptioning"],
            path: "Tests/GurbaniCaptioningTests",
            resources: [
                // Parity-test fixtures dumped from Python.
                .process("Fixtures"),
            ]
        ),
    ]
)
