// swift-tools-version: 5.9
//
// GurbaniCaptioning — on-device live Gurbani kirtan captioning.
//
// Architecture mirrors src/engine.py + src/streaming_engine.py (Python). The
// CaptionEngine class wraps WhisperKit (ANE-accelerated Core ML inference)
// and routes its transcript output through FuzzyMatcher + ShabadStateMachine
// to produce canonical SGGS line predictions.
//
// Open this Package.swift in Xcode — it generates the project tree directly,
// no .xcodeproj hand-authoring needed.
//
// M5.1 (Foundations) added the `SangatApp` library target and a matching
// test target. The `GurbaniCaptioningApp` executable target depends on
// `SangatApp` and is intentionally tiny — just `@main` + a one-line
// `ContentView` redirect. All app-layer code lives in `SangatApp` so it can
// be `@testable import`-ed by the test target. See
// `docs/ios_app_architecture.md` for the rationale.
//
// M5.2 (Sangat reading) introduces:
//   - `Sources/GurbaniCaptioningApp/Info.plist` for iOS app metadata
//     (bundle identifier, mic permission string, supported orientations).
//   - `linkerSettings` block on the executable target that embeds the
//     Info.plist into the binary's `__TEXT,__info_plist` section.
//     This is what makes the app actually launchable on the iOS Simulator
//     — without it, the bundle identifier is nil and UIApplicationMain
//     refuses to start.
//   - The `exclude: ["Info.plist"]` line tells SPM not to treat the plist
//     as a compilable resource; it's metadata consumed by the linker, not
//     code or a runtime asset.
//
//   If the linker-embed approach doesn't fly with your Xcode/toolchain
//   combo (some versions surface the embedded plist on simulator only,
//   others need a real .xcodeproj wrapper), see `docs/ios_app_milestones.md`
//   § "Fallback packaging" for the XcodeGen wrapper recipe.

import PackageDescription

let package = Package(
    name: "GurbaniCaptioning",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(
            name: "GurbaniCaptioning",
            targets: ["GurbaniCaptioning"]
        ),
        // M5.1: App-layer library so the executable stays thin and the test
        // target can `@testable import SangatApp`.
        .library(
            name: "SangatApp",
            targets: ["SangatApp"]
        ),
        .executable(
            name: "GurbaniCaptioningApp",
            targets: ["GurbaniCaptioningApp"]
        ),
    ],
    dependencies: [
        // On-device Whisper inference on Apple Silicon. Argmax's package
        // handles audio capture, Core ML model loading, ANE optimization,
        // word-level timestamps via DTW on cross-attention.
        .package(url: "https://github.com/argmaxinc/WhisperKit", from: "0.9.0"),
    ],
    targets: [
        .target(
            name: "GurbaniCaptioning",
            dependencies: [
                .product(name: "WhisperKit", package: "WhisperKit"),
            ],
            path: "Sources/GurbaniCaptioning",
            resources: [
                // Corpus JSON is generated by scripts/build_ios_corpus.py and
                // dropped into Sources/GurbaniCaptioning/Resources/. The
                // bundle ships it to the device.
                .process("Resources"),
            ]
        ),
        // M5.1: All app-layer UI + state code. Depends only on the
        // GurbaniCaptioning library (the engine), never the other way.
        .target(
            name: "SangatApp",
            dependencies: [
                "GurbaniCaptioning",
            ],
            path: "Sources/SangatApp"
        ),
        .executableTarget(
            name: "GurbaniCaptioningApp",
            dependencies: [
                "GurbaniCaptioning",
                // M5.1: executable now imports SangatApp for RootView etc.
                "SangatApp",
            ],
            path: "Sources/GurbaniCaptioningApp",
            // Info.plist is consumed by the GurbaniCaptioning.xcodeproj wrapper
            // (generated by xcodegen from project.yml). SPM's executable target
            // here remains a macOS-runnable CLI; the iOS simulator runs through
            // the xcodeproj's iOS app target, not this one.
            exclude: [
                "Info.plist",
            ]
        ),
        .testTarget(
            name: "GurbaniCaptioningTests",
            dependencies: ["GurbaniCaptioning"],
            path: "Tests/GurbaniCaptioningTests",
            resources: [
                // Parity-test fixtures dumped from Python.
                .process("Fixtures"),
            ]
        ),
        // M5.1: App-layer tests. Uses `@testable import SangatApp` so test
        // code can reach internal types when needed.
        .testTarget(
            name: "SangatAppTests",
            dependencies: ["SangatApp"],
            path: "Tests/SangatAppTests"
        ),
    ]
)
