//
//  BundledResources.swift
//  GurbaniCaptioning
//
//  Public helpers for tests + downstream callers that want to find
//  the library target's bundled resources. The autogenerated
//  `Bundle.module` is internal to the target by SwiftPM convention;
//  exposing a public API around it is what lets the
//  `GurbaniCaptioningTests` target (which `@testable import`s us)
//  locate the Core ML model directory at runtime.
//
//  Today this is just the Core ML model lookup used by
//  `ModelParityTests`; future bundled assets (e.g., the upcoming
//  `shabads.json` corpus reader) can hang off the same namespace.

import Foundation

/// Public lookups against `Bundle.module` (the library's SPM-
/// generated resource bundle). Returns `nil` when the resource isn't
/// present — callers (notably `CaptionEngine.resolveModelFolder`)
/// translate that into a graceful fallback rather than a crash.
public enum BundledResources {

    /// URL of the bundled Core ML model directory, looked up by
    /// folder name (e.g. `"surt-small-v3-kirtan"`). The directory is
    /// shipped via the `.copy("Resources/<name>")` declaration in
    /// `Package.swift`; absent that declaration (or before
    /// `make ios-bundle-model` populates the directory), this
    /// returns `nil`.
    public static func modelFolderURL(name: String) -> URL? {
        Bundle.module.url(forResource: name, withExtension: nil)
    }
}
